package com.jason.emall.entity;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   此表为购物车表。
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cart
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Cart {
    /**
     * Database Column Remarks:
     *   购物车id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.ct_id
     *
     * @mbg.generated
     */
    private Integer ctId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.g_id
     *
     * @mbg.generated
     */
    private Integer gId;

    /**
     * Database Column Remarks:
     *   商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.g_count
     *
     * @mbg.generated
     */
    private String gCount;

    /**
     * Database Column Remarks:
     *   商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.g_price
     *
     * @mbg.generated
     */
    private BigDecimal gPrice;

    /**
     * Database Column Remarks:
     *   商品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.g_image
     *
     * @mbg.generated
     */
    private String gImage;

    /**
     * Database Column Remarks:
     *   购物车小计
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.ct_subtotal
     *
     * @mbg.generated
     */
    private BigDecimal ctSubtotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.ct_id
     *
     * @return the value of cart.ct_id
     *
     * @mbg.generated
     */
    public Integer getCtId() {
        return ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.ct_id
     *
     * @param ctId the value for cart.ct_id
     *
     * @mbg.generated
     */
    public void setCtId(Integer ctId) {
        this.ctId = ctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.u_id
     *
     * @return the value of cart.u_id
     *
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.u_id
     *
     * @param uId the value for cart.u_id
     *
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.g_id
     *
     * @return the value of cart.g_id
     *
     * @mbg.generated
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.g_id
     *
     * @param gId the value for cart.g_id
     *
     * @mbg.generated
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.g_count
     *
     * @return the value of cart.g_count
     *
     * @mbg.generated
     */
    public String getgCount() {
        return gCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.g_count
     *
     * @param gCount the value for cart.g_count
     *
     * @mbg.generated
     */
    public void setgCount(String gCount) {
        this.gCount = gCount == null ? null : gCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.g_price
     *
     * @return the value of cart.g_price
     *
     * @mbg.generated
     */
    public BigDecimal getgPrice() {
        return gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.g_price
     *
     * @param gPrice the value for cart.g_price
     *
     * @mbg.generated
     */
    public void setgPrice(BigDecimal gPrice) {
        this.gPrice = gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.g_image
     *
     * @return the value of cart.g_image
     *
     * @mbg.generated
     */
    public String getgImage() {
        return gImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.g_image
     *
     * @param gImage the value for cart.g_image
     *
     * @mbg.generated
     */
    public void setgImage(String gImage) {
        this.gImage = gImage == null ? null : gImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.ct_subtotal
     *
     * @return the value of cart.ct_subtotal
     *
     * @mbg.generated
     */
    public BigDecimal getCtSubtotal() {
        return ctSubtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.ct_subtotal
     *
     * @param ctSubtotal the value for cart.ct_subtotal
     *
     * @mbg.generated
     */
    public void setCtSubtotal(BigDecimal ctSubtotal) {
        this.ctSubtotal = ctSubtotal;
    }
}