package com.jason.emall.entity;

/**
 * Database Table Remarks:
 *   此表为商品类别表。
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table category
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Category {
    /**
     * Database Column Remarks:
     *   商品类别id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     * Database Column Remarks:
     *   商品类别名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     * Database Column Remarks:
     *   商品类别父类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.c_parent
     *
     * @mbg.generated
     */
    private Integer cParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.c_id
     *
     * @return the value of category.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.c_id
     *
     * @param cId the value for category.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.c_name
     *
     * @return the value of category.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.c_name
     *
     * @param cName the value for category.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.c_parent
     *
     * @return the value of category.c_parent
     *
     * @mbg.generated
     */
    public Integer getcParent() {
        return cParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.c_parent
     *
     * @param cParent the value for category.c_parent
     *
     * @mbg.generated
     */
    public void setcParent(Integer cParent) {
        this.cParent = cParent;
    }
}