package com.jason.emall.entity;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   此表为商品表。
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table goods
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Goods {
    /**
     * Database Column Remarks:
     *   商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_id
     *
     * @mbg.generated
     */
    private Integer gId;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_name
     *
     * @mbg.generated
     */
    private String gName;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_describe
     *
     * @mbg.generated
     */
    private String gDescribe;

    /**
     * Database Column Remarks:
     *   商品类别id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     * Database Column Remarks:
     *   商品库存
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_stock
     *
     * @mbg.generated
     */
    private Integer gStock;

    /**
     * Database Column Remarks:
     *   商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_price
     *
     * @mbg.generated
     */
    private BigDecimal gPrice;

    /**
     * Database Column Remarks:
     *   商品图片地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_image
     *
     * @mbg.generated
     */
    private String gImage;

    /**
     * Database Column Remarks:
     *   商品详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_details
     *
     * @mbg.generated
     */
    private String gDetails;

    /**
     * Database Column Remarks:
     *   商品状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.g_status
     *
     * @mbg.generated
     */
    private Integer gStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_id
     *
     * @return the value of goods.g_id
     *
     * @mbg.generated
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_id
     *
     * @param gId the value for goods.g_id
     *
     * @mbg.generated
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_name
     *
     * @return the value of goods.g_name
     *
     * @mbg.generated
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_name
     *
     * @param gName the value for goods.g_name
     *
     * @mbg.generated
     */
    public void setgName(String gName) {
        this.gName = gName == null ? null : gName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_describe
     *
     * @return the value of goods.g_describe
     *
     * @mbg.generated
     */
    public String getgDescribe() {
        return gDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_describe
     *
     * @param gDescribe the value for goods.g_describe
     *
     * @mbg.generated
     */
    public void setgDescribe(String gDescribe) {
        this.gDescribe = gDescribe == null ? null : gDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.c_id
     *
     * @return the value of goods.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.c_id
     *
     * @param cId the value for goods.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_stock
     *
     * @return the value of goods.g_stock
     *
     * @mbg.generated
     */
    public Integer getgStock() {
        return gStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_stock
     *
     * @param gStock the value for goods.g_stock
     *
     * @mbg.generated
     */
    public void setgStock(Integer gStock) {
        this.gStock = gStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_price
     *
     * @return the value of goods.g_price
     *
     * @mbg.generated
     */
    public BigDecimal getgPrice() {
        return gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_price
     *
     * @param gPrice the value for goods.g_price
     *
     * @mbg.generated
     */
    public void setgPrice(BigDecimal gPrice) {
        this.gPrice = gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_image
     *
     * @return the value of goods.g_image
     *
     * @mbg.generated
     */
    public String getgImage() {
        return gImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_image
     *
     * @param gImage the value for goods.g_image
     *
     * @mbg.generated
     */
    public void setgImage(String gImage) {
        this.gImage = gImage == null ? null : gImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_details
     *
     * @return the value of goods.g_details
     *
     * @mbg.generated
     */
    public String getgDetails() {
        return gDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_details
     *
     * @param gDetails the value for goods.g_details
     *
     * @mbg.generated
     */
    public void setgDetails(String gDetails) {
        this.gDetails = gDetails == null ? null : gDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.g_status
     *
     * @return the value of goods.g_status
     *
     * @mbg.generated
     */
    public Integer getgStatus() {
        return gStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.g_status
     *
     * @param gStatus the value for goods.g_status
     *
     * @mbg.generated
     */
    public void setgStatus(Integer gStatus) {
        this.gStatus = gStatus;
    }
}