package com.jason.emall.entity;

import java.math.BigDecimal;

/**
 * Database Table Remarks:
 *   此表为订单明细表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table orderitem
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OrderItem {
    /**
     * Database Column Remarks:
     *   订单明细id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.ot_id
     *
     * @mbg.generated
     */
    private Integer otId;

    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.o_id
     *
     * @mbg.generated
     */
    private Integer oId;

    /**
     * Database Column Remarks:
     *   订单用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     * Database Column Remarks:
     *   订单商品id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.g_id
     *
     * @mbg.generated
     */
    private Integer gId;

    /**
     * Database Column Remarks:
     *   订单商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.g_name
     *
     * @mbg.generated
     */
    private String gName;

    /**
     * Database Column Remarks:
     *   订单商品图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.g_image
     *
     * @mbg.generated
     */
    private String gImage;

    /**
     * Database Column Remarks:
     *   订单商品价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.g_price
     *
     * @mbg.generated
     */
    private BigDecimal gPrice;

    /**
     * Database Column Remarks:
     *   订单商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.g_count
     *
     * @mbg.generated
     */
    private String gCount;

    /**
     * Database Column Remarks:
     *   订单明细小计
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.ot_subtotal
     *
     * @mbg.generated
     */
    private BigDecimal otSubtotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.ot_id
     *
     * @return the value of orderitem.ot_id
     *
     * @mbg.generated
     */
    public Integer getOtId() {
        return otId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.ot_id
     *
     * @param otId the value for orderitem.ot_id
     *
     * @mbg.generated
     */
    public void setOtId(Integer otId) {
        this.otId = otId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.o_id
     *
     * @return the value of orderitem.o_id
     *
     * @mbg.generated
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.o_id
     *
     * @param oId the value for orderitem.o_id
     *
     * @mbg.generated
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.u_id
     *
     * @return the value of orderitem.u_id
     *
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.u_id
     *
     * @param uId the value for orderitem.u_id
     *
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.g_id
     *
     * @return the value of orderitem.g_id
     *
     * @mbg.generated
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.g_id
     *
     * @param gId the value for orderitem.g_id
     *
     * @mbg.generated
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.g_name
     *
     * @return the value of orderitem.g_name
     *
     * @mbg.generated
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.g_name
     *
     * @param gName the value for orderitem.g_name
     *
     * @mbg.generated
     */
    public void setgName(String gName) {
        this.gName = gName == null ? null : gName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.g_image
     *
     * @return the value of orderitem.g_image
     *
     * @mbg.generated
     */
    public String getgImage() {
        return gImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.g_image
     *
     * @param gImage the value for orderitem.g_image
     *
     * @mbg.generated
     */
    public void setgImage(String gImage) {
        this.gImage = gImage == null ? null : gImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.g_price
     *
     * @return the value of orderitem.g_price
     *
     * @mbg.generated
     */
    public BigDecimal getgPrice() {
        return gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.g_price
     *
     * @param gPrice the value for orderitem.g_price
     *
     * @mbg.generated
     */
    public void setgPrice(BigDecimal gPrice) {
        this.gPrice = gPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.g_count
     *
     * @return the value of orderitem.g_count
     *
     * @mbg.generated
     */
    public String getgCount() {
        return gCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.g_count
     *
     * @param gCount the value for orderitem.g_count
     *
     * @mbg.generated
     */
    public void setgCount(String gCount) {
        this.gCount = gCount == null ? null : gCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.ot_subtotal
     *
     * @return the value of orderitem.ot_subtotal
     *
     * @mbg.generated
     */
    public BigDecimal getOtSubtotal() {
        return otSubtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.ot_subtotal
     *
     * @param otSubtotal the value for orderitem.ot_subtotal
     *
     * @mbg.generated
     */
    public void setOtSubtotal(BigDecimal otSubtotal) {
        this.otSubtotal = otSubtotal;
    }
}