package com.jason.emall.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   此表为订单表。
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Order {
    /**
     * Database Column Remarks:
     *   订单id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_id
     *
     * @mbg.generated
     */
    private Integer oId;

    /**
     * Database Column Remarks:
     *   订单用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     * Database Column Remarks:
     *   订单总付款
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_payment
     *
     * @mbg.generated
     */
    private String oPayment;

    /**
     * Database Column Remarks:
     *   订单状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_status
     *
     * @mbg.generated
     */
    private String oStatus;

    /**
     * Database Column Remarks:
     *   订单创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_create_time
     *
     * @mbg.generated
     */
    private Date oCreateTime;

    /**
     * Database Column Remarks:
     *   订单支付时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_payment_time
     *
     * @mbg.generated
     */
    private Date oPaymentTime;

    /**
     * Database Column Remarks:
     *   订单商品发送时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_send_time
     *
     * @mbg.generated
     */
    private Date oSendTime;

    /**
     * Database Column Remarks:
     *   订单完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.o_end_time
     *
     * @mbg.generated
     */
    private Date oEndTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_id
     *
     * @return the value of order.o_id
     *
     * @mbg.generated
     */
    public Integer getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_id
     *
     * @param oId the value for order.o_id
     *
     * @mbg.generated
     */
    public void setoId(Integer oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.u_id
     *
     * @return the value of order.u_id
     *
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.u_id
     *
     * @param uId the value for order.u_id
     *
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_payment
     *
     * @return the value of order.o_payment
     *
     * @mbg.generated
     */
    public String getoPayment() {
        return oPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_payment
     *
     * @param oPayment the value for order.o_payment
     *
     * @mbg.generated
     */
    public void setoPayment(String oPayment) {
        this.oPayment = oPayment == null ? null : oPayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_status
     *
     * @return the value of order.o_status
     *
     * @mbg.generated
     */
    public String getoStatus() {
        return oStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_status
     *
     * @param oStatus the value for order.o_status
     *
     * @mbg.generated
     */
    public void setoStatus(String oStatus) {
        this.oStatus = oStatus == null ? null : oStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_create_time
     *
     * @return the value of order.o_create_time
     *
     * @mbg.generated
     */
    public Date getoCreateTime() {
        return oCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_create_time
     *
     * @param oCreateTime the value for order.o_create_time
     *
     * @mbg.generated
     */
    public void setoCreateTime(Date oCreateTime) {
        this.oCreateTime = oCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_payment_time
     *
     * @return the value of order.o_payment_time
     *
     * @mbg.generated
     */
    public Date getoPaymentTime() {
        return oPaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_payment_time
     *
     * @param oPaymentTime the value for order.o_payment_time
     *
     * @mbg.generated
     */
    public void setoPaymentTime(Date oPaymentTime) {
        this.oPaymentTime = oPaymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_send_time
     *
     * @return the value of order.o_send_time
     *
     * @mbg.generated
     */
    public Date getoSendTime() {
        return oSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_send_time
     *
     * @param oSendTime the value for order.o_send_time
     *
     * @mbg.generated
     */
    public void setoSendTime(Date oSendTime) {
        this.oSendTime = oSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.o_end_time
     *
     * @return the value of order.o_end_time
     *
     * @mbg.generated
     */
    public Date getoEndTime() {
        return oEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.o_end_time
     *
     * @param oEndTime the value for order.o_end_time
     *
     * @mbg.generated
     */
    public void setoEndTime(Date oEndTime) {
        this.oEndTime = oEndTime;
    }
}