package com.jason.emall.entity;

/**
 * Database Table Remarks:
 *   此表为用户表。
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class User {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_id
     *
     * @mbg.generated
     */
    private Integer uId;

    /**
     * Database Column Remarks:
     *   用户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_name
     *
     * @mbg.generated
     */
    private String uName;

    /**
     * Database Column Remarks:
     *   用户密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_password
     *
     * @mbg.generated
     */
    private String uPassword;

    /**
     * Database Column Remarks:
     *   用户性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_sex
     *
     * @mbg.generated
     */
    private String uSex;

    /**
     * Database Column Remarks:
     *   用户手机号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_mobile_number
     *
     * @mbg.generated
     */
    private String uMobileNumber;

    /**
     * Database Column Remarks:
     *   用户角色
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.u_role
     *
     * @mbg.generated
     */
    private Integer uRole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_id
     *
     * @return the value of user.u_id
     *
     * @mbg.generated
     */
    public Integer getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_id
     *
     * @param uId the value for user.u_id
     *
     * @mbg.generated
     */
    public void setuId(Integer uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_name
     *
     * @return the value of user.u_name
     *
     * @mbg.generated
     */
    public String getuName() {
        return uName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_name
     *
     * @param uName the value for user.u_name
     *
     * @mbg.generated
     */
    public void setuName(String uName) {
        this.uName = uName == null ? null : uName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_password
     *
     * @return the value of user.u_password
     *
     * @mbg.generated
     */
    public String getuPassword() {
        return uPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_password
     *
     * @param uPassword the value for user.u_password
     *
     * @mbg.generated
     */
    public void setuPassword(String uPassword) {
        this.uPassword = uPassword == null ? null : uPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_sex
     *
     * @return the value of user.u_sex
     *
     * @mbg.generated
     */
    public String getuSex() {
        return uSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_sex
     *
     * @param uSex the value for user.u_sex
     *
     * @mbg.generated
     */
    public void setuSex(String uSex) {
        this.uSex = uSex == null ? null : uSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_mobile_number
     *
     * @return the value of user.u_mobile_number
     *
     * @mbg.generated
     */
    public String getuMobileNumber() {
        return uMobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_mobile_number
     *
     * @param uMobileNumber the value for user.u_mobile_number
     *
     * @mbg.generated
     */
    public void setuMobileNumber(String uMobileNumber) {
        this.uMobileNumber = uMobileNumber == null ? null : uMobileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.u_role
     *
     * @return the value of user.u_role
     *
     * @mbg.generated
     */
    public Integer getuRole() {
        return uRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.u_role
     *
     * @param uRole the value for user.u_role
     *
     * @mbg.generated
     */
    public void setuRole(Integer uRole) {
        this.uRole = uRole;
    }
}